"""empty message

Revision ID: 7c2127d3bee3
Revises: 1757945d546f
Create Date: 2019-12-31 19:15:00.424408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c2127d3bee3'
down_revision = '1757945d546f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles_users', sa.Column('users_id', sa.Integer(), nullable=True))
    op.drop_constraint('roles_users_ibfk_2', 'roles_users', type_='foreignkey')
    op.create_foreign_key(None, 'roles_users', 'user', ['users_id'], ['id'])
    op.drop_column('roles_users', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles_users', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.create_foreign_key('roles_users_ibfk_2', 'roles_users', 'user', ['user_id'], ['id'])
    op.drop_column('roles_users', 'users_id')
    # ### end Alembic commands ###
